### ISSUE TITLE
SkyWars

### ISSUE THREAD

**Issue by LewBr** [EmreTr1/PartyGame#1]
Please close this other Minigames and make a party for SkyWars!!

**Comment by LewBr** [comment]
And DropWars doesn't works!

i try to start the game but doesn't work!
http://prntscr.com/e0kixb

**Comment by EmreTr1** [comment]
Thanks for report. I will fix some bugs and complate thr plugin now :)

**Comment by LewBr** [comment]
Please back whit this plugin! xD
